security:
  oauth2:
    client:
      clientId: DellTechnologyAuthServer
      clientSecret: Dellemc
      accessTokenUri: http://localhost:8082/oauth/token
      userAuthorizationUri: http://localhost:8082/oauth/authorize
    resource:
      userInfoUri: http://localhost:8082/auth/validateUser